### ISSUE TITLE
Which is the correct netlify repo?

### ISSUE THREAD

**Issue by LinkCable** [preactjs/preact-netlify#20]
I found this repo and another (https://github.com/preactjs-templates/netlify) related to setting up a preact blog with Netlify.

However the cli references the second one as it's located in the preactjs-templates org. But I see that this repo has more recent commits. 

So which to use, and if this first one, how can I run it from the cli if it's not in the preactjs-templates org?

Also regardless of which repo I use the blog posts don't seem to render on /blogs?

**Comment by prateekbh** [comment]
both repos have different function.
This repo is cloned by the netlify setup whereas the other repo is used by preact-cli.

> Also regardless of which repo I use the blog posts don't seem to render on /blogs?

What exactly is the error you're getting? I just cloned and seems to be working

**Comment by LinkCable** [comment]
@prateekbh must have messed something up somehow, but I get:
`GET http://0.0.0.0:8080/blogs/preact_prerender_data.json 404 (Not Found)`

Not sure why the site is looking for preact-prerender in the blogs path when I navigate to the /blogs route. All I've done so far is add a new component. But yeah the example works, so I'll just restart it.

**Comment by LinkCable** [comment]
hmm okay yeah after I edit the Content folder to introduce a new folder it seems to start breaking for some reason. Same error where it can't find the prerender_data.json

**Comment by prateekbh** [comment]
Thanks for the repro. I'll fix the bug and probably you can copy the diff

**Comment by prateekbh** [comment]
https://github.com/preactjs/preact-netlify/pull/21

**Comment by prateekbh** [comment]
landed the fix
